markdown:         kramdown
safe:             true
lsi:              false
highlighter:      pygments
paginate:         20
paginate_path:    "blog/page:num"
permalink:        /:title

author:
    name:         lastmayday
description:      "lastmayday's Blog"
author_info:      <a href="http://lastmayday.github.io">lastmayday</a>

copyright:
    - Design by <a href="http://lastmayday.github.io" title="lastmayday" target="_blank">lastmayday</a> &copy; 2013-2015

gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]
