markdown:         kramdown
safe:             true
lsi:              false
pygments:         true
paginate:         20
permalink:        /:title

author:
    name:         lastmayday
description:      "lastmayday's Blog"
author_info:      <a href="http://lastmayday.org">lastmayday</a>

copyright:
    - Design by <a href="http://lastmayday.org" title="lastmayday" target="_blank">lastmayday</a> &copy; 2013
